### ISSUE TITLE
Boost cannot find data file

### ISSUE THREAD

**Issue by ZhiWeiCui** [sguo28/DROP_Simulator#1]
I'm very interested in your project, but it fails while running.  

Boost cannot find data file, such as cs_snap_unique.shp, cs_snap_unique.csv.

Not sure if this is intentional. Hope to provide more detailed guidance.

**Comment by sguo28** [comment]
I have uploaded sample data sets (e.g., cs_snap_unique.shp, cs_snap_unique.csv). However, those datasets can be safely removed due to limited functionality regarding this version.

**Comment by ZhiWeiCui** [comment]
Thank you very much for your immediate reply.

I will continue to follow your project and look forward to a more detailed wiki.

My recent work on matching, repositioning and pricing in ride‐hailing.

**Comment by ZhiWeiCui** [comment]
Error parsing _parsed_routes.pkl_

```
Traceback (most recent call last):
  File "/mnt/d/git/DROP_Simulator/code/train_loops.py", line 35, in <module>
    simulator.init(HEX_SHP_PATH, CS_SHP_PATH, TRIP_FILE, TRAVEL_TIME_FILE, NUM_NEAREST_CS)
  File "/mnt/d/git/DROP_Simulator/code/simulator/simulator_cnn.py", line 172, in init
    self.hex_routes=pickle.load(f)
_pickle.UnpicklingError: invalid load key, 'v'.
```

When I regenerated this data file via _routes_interpolate.py_, I found that _all_routes.pkl_ does not exist.

Disturbed again!

**Comment by sguo28** [comment]
"all_routes.pkl" is not included in our simulator. You may try use `ALL_HEX_ROUTE_FILE = '../data/parsed_routes.pkl'
HEX_ROUTE_FILE = '../data/hex_routes.pkl'  # the route between necessary pair of hex zone` interchangeably to make it run. 
You may start with "main_cnn.py".

**Comment by ZhiWeiCui** [comment]
Thanks for your patient reply. Error parsing parsed_routes.pkl has been resolved by the [method](https://stackoverflow.com/a/67141340).   

But unfortunately it says that another file is missing _hex_diffusion.pkl_.  

```Traceback (most recent call last):
  File "/mnt/d/DROP_Simulator/code/main_cnn.py", line 43, in <module>
    simulator.init(HEX_SHP_PATH, CS_SHP_PATH, TRIP_FILE, TRAVEL_TIME_FILE, NUM_NEAREST_CS)
  File "/mnt/d/DROP_Simulator/code/simulator/simulator_cnn.py", line 194, in init
    self.hex_diffusions = self.get_hex_diffusions(HEX_DIFFUSION_PATH, row_col_coords)
  File "/mnt/d/DROP_Simulator/code/simulator/simulator_cnn.py", line 130, in get_hex_diffusions
    with open(diff_file, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '../data/hex_diffusion.pkl
```

It would be great if a script to generate this data from the raw data could be provided !

**Comment by sguo28** [comment]
Hi, I tried to find the original file to generate the diffusion matrix. I will upload the original dataset once I find it. As an alternative, you can tentatively use the code below to bypass the error:
`hex_diffusion={i: [0.1 for _ in range(1347)] for i in range(1347)}`
where 1347 is the total number of hexagon cells in this simulator.

**Comment by ZhiWeiCui** [comment]
I tried the solution you mentioned and still got the following error:

```Traceback (most recent call last):
  File "/home/cuizhiwei/.vscode-server/extensions/ms-python.python-2022.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py", line 247, in eval_in_context
    result = eval(_expression_to_evaluate(expression), globals)
  File "<string>", line 1, in <module>
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 2, the array at index 0 has size 54 and the array at index 1 has size 1
```  


![image](https://user-images.githubusercontent.com/22850130/175848153-21957fe8-30c6-4da7-8011-3aba93b79742.png)

**Comment by sguo28** [comment]
Hi, we have uploaded all large files to OneDrive, which can be accessed [here](https://bama365-my.sharepoint.com/:f:/g/personal/sguo18_crimson_ua_edu/Etn1ZPhQ20ZNicLpYbCKyyQBy8QlqGfm4kmaEbIugTXiew?e=WZD4zz).

**Comment by WahabMam** [comment]
Hello, sorry to bother you can you explain a little bit with details main files(which are more important), i have studies several times you good work, but still I have some confusion regarding your code.
thanks in advance!

**Comment by sguo28** [comment]
Hi, I'm willing to help. Can you specify your confusion?

**Comment by WahabMam** [comment]
Thanks for your reply, actually I am new to research can you please explain
which files I should run for training and which for seeing the result, baby
steps please
Kind Regards

**Comment by sguo28** [comment]
You can start with running `main_cnn.py`. As we're extending this version to an electrified one, more details will be provided. Please stay tuned!

**Comment by WahabMam** [comment]
Thanks for the update, do you have time to give me some instructions I
really need your help, if so I will be owe of you.
Thanks
