### ISSUE TITLE
missing hex_diffusion.pkl file

### ISSUE THREAD

**Issue by WahabMam** [sguo28/DROP_Simulator#3]
This repository is interesting, but when i try to run the code it shows file not found 'hex_diffusion.pkl'.
Please update me in this regard.
![bug](https://user-images.githubusercontent.com/116133863/214526291-c4f0e0fc-d0d0-459c-8c49-b46d3b8182c8.png)

**Comment by sguo28** [comment]
Thanks for reaching out. Those files are large (Github has restrictions for files of >25MB). As an alternative, we provide the pre-processed (large) files via Onedrive, which is available at [here](https://bama365-my.sharepoint.com/:f:/g/personal/sguo18_crimson_ua_edu/Etn1ZPhQ20ZNicLpYbCKyyQBy8QlqGfm4kmaEbIugTXiew?e=WZD4zz).

**Comment by WahabMam** [comment]
Thank you for your help and reply.

**Comment by WahabMam** [comment]
sorry to bother you, can i have your email address please!?
