### ISSUE TITLE
can not find data files——daily_trips/{}.csv

### ISSUE THREAD

**Issue by qq33899** [sguo28/DROP_Simulator#4]
Sorry to bother you, I'm very interested in your good project, but unfortunately, it fails while running.

When I run main_cnn.py, I find that those part of the file("../data/daily_trips/{}.csv") are missing. and I didn't find those part of data in OneDrive.

I use data/trips_ on_ day{}. csv replaced those part of the file, but you only uploaded the 0 to 5 days. Can you upload the following files? Or tell me how to construct those part of data?

thanks in advance!

**Comment by sguo28** [comment]
Thanks for your comment. I have uploaded the data for the first 10 days to the Onedrive. Let me know if it still doesn't work.

**Comment by qq33899** [comment]
Thank you very much for your immediate reply. main_cnn.py can now run for a while.

But unfortunately, main_cnn.py will still report errors without data of 10 to 20 days. Can you give me data for 10 to 20 days? or  tell me how to construct those part of data? I will be very grateful to you.

thanks in advance!

![image](https://user-images.githubusercontent.com/55220195/223606602-28b336ee-a61b-4706-b6d8-08d963bbce8a.png)

![image](https://user-images.githubusercontent.com/55220195/223606310-eb92abc2-4e09-4a1c-9915-3bd852eda0a6.png)

**Comment by sguo28** [comment]
I will upload the remaining file later tomorrow. For now, feel free to
modify the rang(20) to range(10) to avoid the error.

**Comment by sguo28** [comment]
Those files are uploaded.

**Comment by qq33899** [comment]
I truly appreciate your timely help. thanks a million!
